return {
["__unused-renders-m__/tech-icon/generic-bottle-dark"] = true,
["__unused-renders-m__/tech-icon/catalytic-chemistry"] = true,
["__unused-renders-m__/tech-icon/comminution"] = true,
["__unused-renders-m__/tech-icon/computronics"] = true,
["__unused-renders-m__/tech-icon/copper-processing"] = true,
["__unused-renders-m__/tech-icon/electrolysis-transparent"] = true,
["__unused-renders-m__/tech-icon/filtration"] = true,
["__unused-renders-m__/tech-icon/generic-bottle-1"] = true,
["__unused-renders-m__/tech-icon/generic-bottle-2"] = true,
["__unused-renders-m__/tech-icon/generic-bottle-gold"] = true,
["__unused-renders-m__/tech-icon/generic-bottle-green"] = true,
["__unused-renders-m__/tech-icon/generic-bottle-mixture"] = true,
["__unused-renders-m__/tech-icon/glassworking"] = true,
["__unused-renders-m__/tech-icon/iron-processing"] = true,
["__unused-renders-m__/tech-icon/lead-processing"] = true,
["__unused-renders-m__/tech-icon/metallurgy"] = true,
["__unused-renders-m__/tech-icon/packaging"] = true,
["__unused-renders-m__/tech-icon/polymers"] = true,
["__unused-renders-m__/tech-icon/radiochemistry-2"] = true,
["__unused-renders-m__/tech-icon/radiochemistry"] = true,
["__unused-renders-m__/tech-icon/rubber"] = true,
["__unused-renders-m__/tech-icon/synthetic-fibers"] = true,
["__unused-renders-m__/tech-icon/titanium-processing"] = true,
}

