return {
"__unused-renders-m__/tech-icon/generic-bottle-dark",
"__unused-renders-m__/tech-icon/catalytic-chemistry",
"__unused-renders-m__/tech-icon/comminution",
"__unused-renders-m__/tech-icon/computronics",
"__unused-renders-m__/tech-icon/copper-processing",
"__unused-renders-m__/tech-icon/electrolysis-transparent",
"__unused-renders-m__/tech-icon/filtration",
"__unused-renders-m__/tech-icon/generic-bottle-1",
"__unused-renders-m__/tech-icon/generic-bottle-2",
"__unused-renders-m__/tech-icon/generic-bottle-gold",
"__unused-renders-m__/tech-icon/generic-bottle-green",
"__unused-renders-m__/tech-icon/generic-bottle-mixture",
"__unused-renders-m__/tech-icon/glassworking",
"__unused-renders-m__/tech-icon/iron-processing",
"__unused-renders-m__/tech-icon/lead-processing",
"__unused-renders-m__/tech-icon/metallurgy",
"__unused-renders-m__/tech-icon/packaging",
"__unused-renders-m__/tech-icon/polymers",
"__unused-renders-m__/tech-icon/radiochemistry-2",
"__unused-renders-m__/tech-icon/radiochemistry",
"__unused-renders-m__/tech-icon/rubber",
"__unused-renders-m__/tech-icon/synthetic-fibers",
"__unused-renders-m__/tech-icon/titanium-processing",
}

